:apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURReQpNakkzTkRWYUZ3MDBNakE0TURReU1qSTNORFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFETXdKMEp6SE9rdVRnVnNobUdCemhTWkdIMEN1ZDRMU29SVEVlL1pWRUxiQkpiUGJ5RApLUUlSODc5Q2xYUkFZMDh2a3ZnZ3dGYVEzMmJQRXgzKzBHbWljb25xWThlR1ZHTzdGVCs4c2QrNi84RW80UktRCm9waXZ1bTduaDB2M3VsSHFQM3lTMm1XY0x0VXVBSWVhQmU4VkFhOWRpNnJFN21YY1I1RjRHejJ0RDhGKzM2dXcKbCtGam5VbUQvY2dJc3ZVbjIxK09rczhJOGROME5nSy9GV0VHQlkycmQyd1BoL29rakRwQjRIUm9qVkRTMzJyRwpwNC9xbnNiQVpTUllEdFhqSGpxQkxYcm5PbVRqVThiWTNGUHFHRTRRUVc1YktjZ1BOZEZTK2hKcDZqS0RtRXFwCnBSNXFvQlNodGJzNGRUVDdxVEtmK0RaWHVkdTJ3NFBrRGtGYkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJBeWwwcGV5QlpocmViM25LaQpxZ0RucFBRbUVUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQZk8rd2lQSUFuamxPNnNaRURXOTRGaGl4aDkwCm4vZlNVczFzbS9sdDlqV3lzOCtEaUxyYmxGYy9GakNFVzNGWjlCR1h2eFVzMTFGZkZMdHd5M01xSTUzRWlxTUcKWG1RZXovMjFmaCtQS2s2aFdLZGJ0T0h6OUU5MXFnaGlBT1J4elovZEd3dGFrdEFNSm9GeU42MmRZNmJBVktQcgo1YkNVVkRiUjI4OUMzYWZxcjJ1SFNqcFU2bDl2OTVrL3NxakpJMSs2VGYxaVVKVXNZTVhua2JHeDlQZWxEYXlICnZ0NjE0OFhUOERWdlZRVURoNUEyTlBXOUtZOUpseXJ1NVRad1FzTHZFbDNiUXpQYy9oYjBveFQvQjYrb0tqb3AKbWN3dzV6SEUwMkxoSC9XYUR5bXpxUm10WWwxOXNKbm0xN3B3YVZ4aXVKaHR0ODE2b1pBTGJGTmxrdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://eb84ffa0-97b4-4a18-892d-17baa3775704.k8s.ondigitalocean.com
  name: do-nyc1-k8s-13
contexts:
- context:
    cluster: do-nyc1-k8s-13
    user: do-nyc1-k8s-13-admin
  name: do-nyc1-k8s-13
current-context: do-nyc1-k8s-13
users:
- name: do-nyc1-k8s-13-admin
  user:
    token: dop_v1_7fa5486e2fd2111a8769896997cd78bc468215c49400731e44cbd4c92499e7be
